steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', '${_IMAGE_NAME}','--update-secrets=CARE_URL=${_CARE_URL}:latest, BACKEND_PORT=${_BACKEND_PORT}:latest',  '--allow-unauthenticated', '--platform', 'managed', '--image', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--region', '${_DEPLOY_REGION}', '--port', '${_DEPLOY_PORT}', '--timeout', '600']
substitutions:
  _IMAGE_NAME: 'test-web-app-backend'
  _DEPLOY_REGION: 'asia-east1'
  _BACKEND_PORT: 'BACKEND_PORT'
  _DEPLOY_PORT: '7777'
  _CARE_URL: 'CARE_URL'
images:
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}'